// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package k3s

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Node struct {
	Args          []string              `pulumi:"args"`
	Host          string                `pulumi:"host"`
	PrivateKey    string                `pulumi:"privateKey"`
	RuntimeConfig *RuntimeConfiguration `pulumi:"runtimeConfig"`
	User          *string               `pulumi:"user"`
}

// NodeInput is an input type that accepts NodeArgs and NodeOutput values.
// You can construct a concrete instance of `NodeInput` via:
//
//          NodeArgs{...}
type NodeInput interface {
	pulumi.Input

	ToNodeOutput() NodeOutput
	ToNodeOutputWithContext(context.Context) NodeOutput
}

type NodeArgs struct {
	Args          pulumi.StringArrayInput      `pulumi:"args"`
	Host          pulumi.StringInput           `pulumi:"host"`
	PrivateKey    pulumi.StringInput           `pulumi:"privateKey"`
	RuntimeConfig RuntimeConfigurationPtrInput `pulumi:"runtimeConfig"`
	User          pulumi.StringPtrInput        `pulumi:"user"`
}

func (NodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Node)(nil)).Elem()
}

func (i NodeArgs) ToNodeOutput() NodeOutput {
	return i.ToNodeOutputWithContext(context.Background())
}

func (i NodeArgs) ToNodeOutputWithContext(ctx context.Context) NodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeOutput)
}

// NodeArrayInput is an input type that accepts NodeArray and NodeArrayOutput values.
// You can construct a concrete instance of `NodeArrayInput` via:
//
//          NodeArray{ NodeArgs{...} }
type NodeArrayInput interface {
	pulumi.Input

	ToNodeArrayOutput() NodeArrayOutput
	ToNodeArrayOutputWithContext(context.Context) NodeArrayOutput
}

type NodeArray []NodeInput

func (NodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Node)(nil)).Elem()
}

func (i NodeArray) ToNodeArrayOutput() NodeArrayOutput {
	return i.ToNodeArrayOutputWithContext(context.Background())
}

func (i NodeArray) ToNodeArrayOutputWithContext(ctx context.Context) NodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeArrayOutput)
}

type NodeOutput struct{ *pulumi.OutputState }

func (NodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Node)(nil)).Elem()
}

func (o NodeOutput) ToNodeOutput() NodeOutput {
	return o
}

func (o NodeOutput) ToNodeOutputWithContext(ctx context.Context) NodeOutput {
	return o
}

func (o NodeOutput) Args() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Node) []string { return v.Args }).(pulumi.StringArrayOutput)
}

func (o NodeOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v Node) string { return v.Host }).(pulumi.StringOutput)
}

func (o NodeOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v Node) string { return v.PrivateKey }).(pulumi.StringOutput)
}

func (o NodeOutput) RuntimeConfig() RuntimeConfigurationPtrOutput {
	return o.ApplyT(func(v Node) *RuntimeConfiguration { return v.RuntimeConfig }).(RuntimeConfigurationPtrOutput)
}

func (o NodeOutput) User() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Node) *string { return v.User }).(pulumi.StringPtrOutput)
}

type NodeArrayOutput struct{ *pulumi.OutputState }

func (NodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Node)(nil)).Elem()
}

func (o NodeArrayOutput) ToNodeArrayOutput() NodeArrayOutput {
	return o
}

func (o NodeArrayOutput) ToNodeArrayOutputWithContext(ctx context.Context) NodeArrayOutput {
	return o
}

func (o NodeArrayOutput) Index(i pulumi.IntInput) NodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Node {
		return vs[0].([]Node)[vs[1].(int)]
	}).(NodeOutput)
}

type RuntimeConfiguration struct {
	EnableGVisor *bool `pulumi:"enableGVisor"`
}

// RuntimeConfigurationInput is an input type that accepts RuntimeConfigurationArgs and RuntimeConfigurationOutput values.
// You can construct a concrete instance of `RuntimeConfigurationInput` via:
//
//          RuntimeConfigurationArgs{...}
type RuntimeConfigurationInput interface {
	pulumi.Input

	ToRuntimeConfigurationOutput() RuntimeConfigurationOutput
	ToRuntimeConfigurationOutputWithContext(context.Context) RuntimeConfigurationOutput
}

type RuntimeConfigurationArgs struct {
	EnableGVisor pulumi.BoolPtrInput `pulumi:"enableGVisor"`
}

func (RuntimeConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RuntimeConfiguration)(nil)).Elem()
}

func (i RuntimeConfigurationArgs) ToRuntimeConfigurationOutput() RuntimeConfigurationOutput {
	return i.ToRuntimeConfigurationOutputWithContext(context.Background())
}

func (i RuntimeConfigurationArgs) ToRuntimeConfigurationOutputWithContext(ctx context.Context) RuntimeConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuntimeConfigurationOutput)
}

func (i RuntimeConfigurationArgs) ToRuntimeConfigurationPtrOutput() RuntimeConfigurationPtrOutput {
	return i.ToRuntimeConfigurationPtrOutputWithContext(context.Background())
}

func (i RuntimeConfigurationArgs) ToRuntimeConfigurationPtrOutputWithContext(ctx context.Context) RuntimeConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuntimeConfigurationOutput).ToRuntimeConfigurationPtrOutputWithContext(ctx)
}

// RuntimeConfigurationPtrInput is an input type that accepts RuntimeConfigurationArgs, RuntimeConfigurationPtr and RuntimeConfigurationPtrOutput values.
// You can construct a concrete instance of `RuntimeConfigurationPtrInput` via:
//
//          RuntimeConfigurationArgs{...}
//
//  or:
//
//          nil
type RuntimeConfigurationPtrInput interface {
	pulumi.Input

	ToRuntimeConfigurationPtrOutput() RuntimeConfigurationPtrOutput
	ToRuntimeConfigurationPtrOutputWithContext(context.Context) RuntimeConfigurationPtrOutput
}

type runtimeConfigurationPtrType RuntimeConfigurationArgs

func RuntimeConfigurationPtr(v *RuntimeConfigurationArgs) RuntimeConfigurationPtrInput {
	return (*runtimeConfigurationPtrType)(v)
}

func (*runtimeConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RuntimeConfiguration)(nil)).Elem()
}

func (i *runtimeConfigurationPtrType) ToRuntimeConfigurationPtrOutput() RuntimeConfigurationPtrOutput {
	return i.ToRuntimeConfigurationPtrOutputWithContext(context.Background())
}

func (i *runtimeConfigurationPtrType) ToRuntimeConfigurationPtrOutputWithContext(ctx context.Context) RuntimeConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuntimeConfigurationPtrOutput)
}

type RuntimeConfigurationOutput struct{ *pulumi.OutputState }

func (RuntimeConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RuntimeConfiguration)(nil)).Elem()
}

func (o RuntimeConfigurationOutput) ToRuntimeConfigurationOutput() RuntimeConfigurationOutput {
	return o
}

func (o RuntimeConfigurationOutput) ToRuntimeConfigurationOutputWithContext(ctx context.Context) RuntimeConfigurationOutput {
	return o
}

func (o RuntimeConfigurationOutput) ToRuntimeConfigurationPtrOutput() RuntimeConfigurationPtrOutput {
	return o.ToRuntimeConfigurationPtrOutputWithContext(context.Background())
}

func (o RuntimeConfigurationOutput) ToRuntimeConfigurationPtrOutputWithContext(ctx context.Context) RuntimeConfigurationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RuntimeConfiguration) *RuntimeConfiguration {
		return &v
	}).(RuntimeConfigurationPtrOutput)
}

func (o RuntimeConfigurationOutput) EnableGVisor() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v RuntimeConfiguration) *bool { return v.EnableGVisor }).(pulumi.BoolPtrOutput)
}

type RuntimeConfigurationPtrOutput struct{ *pulumi.OutputState }

func (RuntimeConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RuntimeConfiguration)(nil)).Elem()
}

func (o RuntimeConfigurationPtrOutput) ToRuntimeConfigurationPtrOutput() RuntimeConfigurationPtrOutput {
	return o
}

func (o RuntimeConfigurationPtrOutput) ToRuntimeConfigurationPtrOutputWithContext(ctx context.Context) RuntimeConfigurationPtrOutput {
	return o
}

func (o RuntimeConfigurationPtrOutput) Elem() RuntimeConfigurationOutput {
	return o.ApplyT(func(v *RuntimeConfiguration) RuntimeConfiguration {
		if v != nil {
			return *v
		}
		var ret RuntimeConfiguration
		return ret
	}).(RuntimeConfigurationOutput)
}

func (o RuntimeConfigurationPtrOutput) EnableGVisor() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RuntimeConfiguration) *bool {
		if v == nil {
			return nil
		}
		return v.EnableGVisor
	}).(pulumi.BoolPtrOutput)
}

type VersionConfiguration struct {
	Channel *string `pulumi:"channel"`
	Version *string `pulumi:"version"`
}

// VersionConfigurationInput is an input type that accepts VersionConfigurationArgs and VersionConfigurationOutput values.
// You can construct a concrete instance of `VersionConfigurationInput` via:
//
//          VersionConfigurationArgs{...}
type VersionConfigurationInput interface {
	pulumi.Input

	ToVersionConfigurationOutput() VersionConfigurationOutput
	ToVersionConfigurationOutputWithContext(context.Context) VersionConfigurationOutput
}

type VersionConfigurationArgs struct {
	Channel pulumi.StringPtrInput `pulumi:"channel"`
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (VersionConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VersionConfiguration)(nil)).Elem()
}

func (i VersionConfigurationArgs) ToVersionConfigurationOutput() VersionConfigurationOutput {
	return i.ToVersionConfigurationOutputWithContext(context.Background())
}

func (i VersionConfigurationArgs) ToVersionConfigurationOutputWithContext(ctx context.Context) VersionConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VersionConfigurationOutput)
}

func (i VersionConfigurationArgs) ToVersionConfigurationPtrOutput() VersionConfigurationPtrOutput {
	return i.ToVersionConfigurationPtrOutputWithContext(context.Background())
}

func (i VersionConfigurationArgs) ToVersionConfigurationPtrOutputWithContext(ctx context.Context) VersionConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VersionConfigurationOutput).ToVersionConfigurationPtrOutputWithContext(ctx)
}

// VersionConfigurationPtrInput is an input type that accepts VersionConfigurationArgs, VersionConfigurationPtr and VersionConfigurationPtrOutput values.
// You can construct a concrete instance of `VersionConfigurationPtrInput` via:
//
//          VersionConfigurationArgs{...}
//
//  or:
//
//          nil
type VersionConfigurationPtrInput interface {
	pulumi.Input

	ToVersionConfigurationPtrOutput() VersionConfigurationPtrOutput
	ToVersionConfigurationPtrOutputWithContext(context.Context) VersionConfigurationPtrOutput
}

type versionConfigurationPtrType VersionConfigurationArgs

func VersionConfigurationPtr(v *VersionConfigurationArgs) VersionConfigurationPtrInput {
	return (*versionConfigurationPtrType)(v)
}

func (*versionConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VersionConfiguration)(nil)).Elem()
}

func (i *versionConfigurationPtrType) ToVersionConfigurationPtrOutput() VersionConfigurationPtrOutput {
	return i.ToVersionConfigurationPtrOutputWithContext(context.Background())
}

func (i *versionConfigurationPtrType) ToVersionConfigurationPtrOutputWithContext(ctx context.Context) VersionConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VersionConfigurationPtrOutput)
}

type VersionConfigurationOutput struct{ *pulumi.OutputState }

func (VersionConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VersionConfiguration)(nil)).Elem()
}

func (o VersionConfigurationOutput) ToVersionConfigurationOutput() VersionConfigurationOutput {
	return o
}

func (o VersionConfigurationOutput) ToVersionConfigurationOutputWithContext(ctx context.Context) VersionConfigurationOutput {
	return o
}

func (o VersionConfigurationOutput) ToVersionConfigurationPtrOutput() VersionConfigurationPtrOutput {
	return o.ToVersionConfigurationPtrOutputWithContext(context.Background())
}

func (o VersionConfigurationOutput) ToVersionConfigurationPtrOutputWithContext(ctx context.Context) VersionConfigurationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VersionConfiguration) *VersionConfiguration {
		return &v
	}).(VersionConfigurationPtrOutput)
}

func (o VersionConfigurationOutput) Channel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VersionConfiguration) *string { return v.Channel }).(pulumi.StringPtrOutput)
}

func (o VersionConfigurationOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VersionConfiguration) *string { return v.Version }).(pulumi.StringPtrOutput)
}

type VersionConfigurationPtrOutput struct{ *pulumi.OutputState }

func (VersionConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VersionConfiguration)(nil)).Elem()
}

func (o VersionConfigurationPtrOutput) ToVersionConfigurationPtrOutput() VersionConfigurationPtrOutput {
	return o
}

func (o VersionConfigurationPtrOutput) ToVersionConfigurationPtrOutputWithContext(ctx context.Context) VersionConfigurationPtrOutput {
	return o
}

func (o VersionConfigurationPtrOutput) Elem() VersionConfigurationOutput {
	return o.ApplyT(func(v *VersionConfiguration) VersionConfiguration {
		if v != nil {
			return *v
		}
		var ret VersionConfiguration
		return ret
	}).(VersionConfigurationOutput)
}

func (o VersionConfigurationPtrOutput) Channel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VersionConfiguration) *string {
		if v == nil {
			return nil
		}
		return v.Channel
	}).(pulumi.StringPtrOutput)
}

func (o VersionConfigurationPtrOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VersionConfiguration) *string {
		if v == nil {
			return nil
		}
		return v.Version
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NodeInput)(nil)).Elem(), NodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodeArrayInput)(nil)).Elem(), NodeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuntimeConfigurationInput)(nil)).Elem(), RuntimeConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuntimeConfigurationPtrInput)(nil)).Elem(), RuntimeConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VersionConfigurationInput)(nil)).Elem(), VersionConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VersionConfigurationPtrInput)(nil)).Elem(), VersionConfigurationArgs{})
	pulumi.RegisterOutputType(NodeOutput{})
	pulumi.RegisterOutputType(NodeArrayOutput{})
	pulumi.RegisterOutputType(RuntimeConfigurationOutput{})
	pulumi.RegisterOutputType(RuntimeConfigurationPtrOutput{})
	pulumi.RegisterOutputType(VersionConfigurationOutput{})
	pulumi.RegisterOutputType(VersionConfigurationPtrOutput{})
}
