// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K3s.Outputs
{

    [OutputType]
    public sealed class CRIConfiguration
    {
        public readonly bool? EnableGVisor;

        [OutputConstructor]
        private CRIConfiguration(bool? enableGVisor)
        {
            EnableGVisor = enableGVisor;
        }
    }
}
