// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K3s.Outputs
{

    [OutputType]
    public sealed class Node
    {
        public readonly ImmutableArray<string> Args;
        public readonly string Host;
        public readonly string PrivateKey;
        public readonly string? User;

        [OutputConstructor]
        private Node(
            ImmutableArray<string> args,

            string host,

            string privateKey,

            string? user)
        {
            Args = args;
            Host = host;
            PrivateKey = privateKey;
            User = user;
        }
    }
}
