// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K3s.Outputs
{

    [OutputType]
    public sealed class VersionConfiguration
    {
        public readonly string? Channel;
        public readonly string? Version;

        [OutputConstructor]
        private VersionConfiguration(
            string? channel,

            string? version)
        {
            Channel = channel;
            Version = version;
        }
    }
}
