// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export interface CRIConfigurationArgs {
    enableGVisor?: pulumi.Input<boolean>;
}

export interface NodeArgs {
    args?: pulumi.Input<pulumi.Input<string>[]>;
    criConfig?: pulumi.Input<inputs.CRIConfigurationArgs>;
    host: pulumi.Input<string>;
    privateKey: pulumi.Input<string>;
    user?: pulumi.Input<string>;
}
/**
 * nodeArgsProvideDefaults sets the appropriate defaults for NodeArgs
 */
export function nodeArgsProvideDefaults(val: NodeArgs): NodeArgs {
    return {
        ...val,
        user: (val.user) ?? "root",
    };
}

export interface VersionConfigurationArgs {
    channel?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}
