// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface CRIConfigurationArgs {
    enableGVisor?: pulumi.Input<boolean>;
}

export interface NodeArgs {
    args?: pulumi.Input<pulumi.Input<string>[]>;
    criConfig?: pulumi.Input<inputs.CRIConfigurationArgs>;
    host: pulumi.Input<string>;
    privateKey: pulumi.Input<string>;
    user?: pulumi.Input<string>;
}

export interface VersionConfigurationArgs {
    channel?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}
