// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Node {
    args?: string[];
    host: string;
    privateKey: string;
    user?: string;
}

export interface VersionConfiguration {
    channel?: string;
    version?: string;
}

