// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export interface CRIConfiguration {
    enableGVisor?: boolean;
}

export interface Node {
    args?: string[];
    criConfig?: outputs.CRIConfiguration;
    host: string;
    privateKey: string;
    user?: string;
}
/**
 * nodeProvideDefaults sets the appropriate defaults for Node
 */
export function nodeProvideDefaults(val: Node): Node {
    return {
        ...val,
        user: (val.user) ?? "root",
    };
}

export interface VersionConfiguration {
    channel?: string;
    version?: string;
}

