// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K3s.Inputs
{

    public sealed class NodeArgs : Pulumi.ResourceArgs
    {
        [Input("args")]
        private InputList<string>? _args;
        public InputList<string> Args
        {
            get => _args ?? (_args = new InputList<string>());
            set => _args = value;
        }

        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        [Input("privateKey", required: true)]
        public Input<string> PrivateKey { get; set; } = null!;

        [Input("runtimeConfig")]
        public Input<Inputs.RuntimeConfigurationArgs>? RuntimeConfig { get; set; }

        [Input("user")]
        public Input<string>? User { get; set; }

        public NodeArgs()
        {
            User = "root";
        }
    }
}
